spring.application.name=Gogobuy


spring.datasource.url=jdbc:mysql://100.98.21.98:3306/gogobuy?serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
spring.datasource.username=gogobuy
spring.datasource.password=gogobuy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# Session 
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# Google OAuth2 
spring.security.oauth2.client.registration.google.client-id=1089363711944-ol65hqmvt877g40r9hifhtpt9gs8ji03.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile